//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace MainCharacter
{
	public class ColorPower
	{
		private float _powRed, _powBlue, _powYellow;

		public float powerRed{ 
			get{lock(syncLock) return _powRed;} 
			set{lock(syncLock) _powRed = value;}
		}

		public float powerBlue{ 
			get{lock(syncLock) return _powBlue;} 
			set{lock(syncLock) _powBlue = value;}
		}
		public float powerYellow{ 
			get{lock(syncLock) return _powYellow;} 
			set{lock(syncLock) _powYellow = value;}
		}

		private readonly static object syncLock = new object();

		
		public static ColorPower _inst;

		public static ColorPower Instance{
			get{
				if(_inst == null){
					_inst = new ColorPower();
				}
				return _inst;
			}
		}
	}
}